[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Remove bytecode hash at the end of compiled bytecode
bytecode_hash = "none"

# Optimizer config
optimizer = true
optimizer_runs = 100_000
via-ir = false