# Global default config
[profile.default]
fs_permissions = [
  { access = "read-write", path = "./external"},
  { access = "read-write", path = "./bin"}
]
bytecode_hash = "none"

# Optimizer config
optimizer = true
optimizer_runs = 100_000
via-ir = false
optimizer_details = { yul = true, constantOptimizer = true }

# Testing
fuzz = { runs = 128, seed = "0xacab" }
invariant = { runs = 128, seed = "0xacab", depth = 500, call_override = true }

# Formatter config
fmt = { sort_imports = true, line_length = 120, number_underscore = "thousands", wrap_comments = true }

# Heavy profile fat testing
[profile.heavy]
Fuzz = { runs = 1024, seed = "0xacab" }
invariant = { runs = 1024, seed = "0xacab", depth = 10_000, call_override = true }

# Etherscan keys
[etherscan]
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  goerli = { key = "${API_KEY_ETHERSCAN}", url = "https://api-goerli.etherscan.io/api" }
  polygon = { key = "${API_KEY_POLYGONSCAN}", url = "https://api.polygonscan.com/api" }
  mumbai = { key = "${API_KEY_POLYGONSCAN}", url = "https://api-testnet.polygonscan.com/api" }
  arbitrum = { key = "${API_KEY_ARBISCAN}", url = "https://api.arbiscan.io/api" }
  arbitrumSepolia = { key = "${API_KEY_ARBISCAN}", url = "https://api-sepolia.arbiscan.io/api" }