[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Remove bytecode hash at the end of compiled bytecode
bytecode_hash = "none"

# Optimizer config
optimizer = true
optimizer_runs = 100_000
via-ir = false


[etherscan]
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  goerli = { key = "${API_KEY_ETHERSCAN}", url = "https://api-goerli.etherscan.io/api" }
  polygon = { key = "${API_KEY_POLYGONSCAN}", url = "https://api.polygonscan.com/api" }
  mumbai = { key = "${API_KEY_POLYGONSCAN}", url = "https://api-testnet.polygonscan.com/api" }